### ISSUE TITLE
I dont see any accounts.exe in zip file.

### ISSUE THREAD

**Issue by faststare** [nikkilocke/AccountServer#4]

**Comment by faststare** [comment]
I dont see any exe file . i ran  netsh http add urlacl url=http://+:8080/  with admin cmd but I'm having a hard time to figure out where exe file with your project sir. do I need to compile the zip file? sorry I'm not familiar with js nor c# language.

**Comment by nikkilocke** [comment]
AccountServer.exe is the first file in the zip. On 19 Mar 2017 8:05 pm, faststare <notifications@github.com> wrote:I dont see any exe file . i ran  netsh http add urlacl url=http://+:8080/  with admin cmd but I'm having a hard time to figure out where exe file with your project sir. do I need to compile the zip file? sorry I'm not familiar with js nor c# language.

**Comment by faststare** [comment]
it seems Purchase Ledger in your AP module have only one type. how I select other ap accounts?

**Comment by nikkilocke** [comment]
I'm not sure why you would want to. The purchase ledger account is used for all accounts payable automatically. I guess you could put in a journal to move some of the purchase ledger amount to another account. Perhaps if you could explain why you want it, I could look at changing the program. Ideally with a reference to how you would do the same thing in Quick Books or Quicken? On 20 Mar 2017 4:33 am, faststare <notifications@github.com> wrote:it seems Purchase Ledger in your AP module have only one type. how I select other ap accounts?

**Comment by faststare** [comment]
as an accountant, we create subclass of accounts payable to simply the bookkeeping. let say I want an accounts payable for trade, I will create accounts payable - trade then if I create another accounts payable for trade others, I will create accounts - trade payable. can you share the pseudo code of your program? I can't read c++ language because I just started to learn python programming language. tia

**Comment by nikkilocke** [comment]
Can you point me to how you would do that in Quick Books? Pseudo code is simple - there is a known, fixed Purchase Ledger account, and posting an invoice automatically creates a journal between that and the lines on the invoice. There is, as always, a conflict between providing maximum functionality, and keeping the user interface simple. I am reluctant to create an additional option (which P/L account to use) on every invoice, unless a significant percentage of users require it. Regards Nikki On 22 Mar 2017 9:03 am, faststare <notifications@github.com> wrote:as an accountant, we create subclass of accounts payable to simply the bookkeeping. let say I want an accounts payable for trade, I will create accounts payable - trade then if I create another accounts payable for trade others, I will create accounts - trade payable. can you share the pseudo code of your program? I can't read c++ language because I just started to learn python programming language. tia

**Comment by faststare** [comment]
I just create an accounts(under chart of accounts module of QB) that subclass of current accounts payable. when I enter/new bills, I can choose two types of accounts payable. it helps the accountant to classify the transactions. when I mean pseudo code, what tables involved and how you query things in that tables. simple example sql language can help me alot. tia
